[package]
name = "nnf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["graphviz"]
graphviz = ["dot-writer"]

[dependencies]
dot-writer = { version = "0.1", optional = true }